# Generated by Django 4.1.2 on 2022-11-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('cafe_name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Cafe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('reviewer_name', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=512)),
            ],
            options={
                'db_table': 'Review',
                'managed': False,
            },
        ),
    ]
