# Generated by Django 4.1.2 on 2022-10-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('charactor', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('Location', models.CharField(max_length=100)),
            ],
        ),
    ]
